LEVEL_NAMES = [
    'LEVEL_NULL',  # -1
    'LEVEL_KARATE_MAN',  # 0
    'LEVEL_KARATE_MAN_2',  # 1
    'LEVEL_CLAPPY_TRIO',  # 2
    'LEVEL_SNAPPY_TRIO',  # 3...
    'LEVEL_POLYRHYTHM',
    'LEVEL_POLYRHYTHM_2',
    'LEVEL_NIGHT_WALK',
    'LEVEL_NIGHT_WALK_2',
    'LEVEL_RHYTHM_TWEEZERS',
    'LEVEL_RHYTHM_TWEEZERS_2',
    'LEVEL_SICK_BEATS',
    'LEVEL_BOUNCY_ROAD',
    'LEVEL_BOUNCY_ROAD_2',
    'LEVEL_NINJA_BODYGUARD',
    'LEVEL_NINJA_REINCARNATE',
    'LEVEL_SNEAKY_SPIRITS',
    'LEVEL_SNEAKY_SPIRITS_2',
    'LEVEL_SAMURAI_SLICE',
    'LEVEL_SPACEBALL',
    'LEVEL_SPACEBALL_2',
    'LEVEL_TAP_TRIAL',
    'LEVEL_TAP_TRIAL_2',
    'LEVEL_MARCHING_ORDERS',
    'LEVEL_MARCHING_ORDERS_2',
    'LEVEL_WIZARDS_WALTZ',
    'LEVEL_BUNNY_HOP',
    'LEVEL_FIREWORKS',
    'LEVEL_POWER_CALLIGRAPHY',
    'LEVEL_POWER_CALLIGRAPHY_2',
    'LEVEL_TOSS_BOYS',
    'LEVEL_TOSS_BOYS_2',
    'LEVEL_RAT_RACE',
    'LEVEL_TRAM_PAULINE',
    'LEVEL_SHOWTIME',
    'LEVEL_SPACE_DANCE',
    'LEVEL_COSMIC_DANCE',
    'LEVEL_RAP_MEN',
    'LEVEL_RAP_WOMEN',
    'LEVEL_QUIZ_SHOW',
    'LEVEL_BON_ODORI',
    'LEVEL_BON_DANCE',
    'LEVEL_REMIX_1',
    'LEVEL_REMIX_2',
    'LEVEL_REMIX_3',
    'LEVEL_REMIX_4',
    'LEVEL_REMIX_5',
    'LEVEL_REMIX_6',
    'LEVEL_REMIX_7',
    'LEVEL_REMIX_8',
    'LEVEL_CAFE',
    'LEVEL_RHYTHM_TOYS',
    'LEVEL_ENDLESS_GAMES',
    'LEVEL_DRUM_LESSONS',
    'LEVEL_STAFF_CREDIT',
    'LEVEL_LIVE_MENU'
]

LEVEL_STATES = [
    'LEVEL_STATE_NULL',  # -1
    'LEVEL_STATE_HIDDEN',  # 0
    'LEVEL_STATE_APPEARING',  # 1
    'LEVEL_STATE_CLOSED',  # 2
    'LEVEL_STATE_OPEN',  # 3...
    'LEVEL_STATE_CLEARED',
    'LEVEL_STATE_HAS_MEDAL'
]

LEVEL_FLAGS = [
    'TARGET_ON_SHOW',  # 0
    'MOVE_CURSOR',  # 1
    'CLEAR_BY_DEFAULT',  # 2
    'DELAY_CLEAR',  # 3...
    'DELAY_OPEN',
    'DELAY_SHOW',
    'TARGET_ON_OPEN'
]
